/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testing;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class location6 extends javax.swing.JFrame {

    /**
     * Creates new form location6
     */
    public location6() {
        initComponents();
         setIconImage();
        
        Icon i = bgimage.getIcon();
        ImageIcon icon =(ImageIcon)i;
        Image image = icon.getImage().getScaledInstance(bgimage.getWidth(), bgimage.getHeight(), Image.SCALE_SMOOTH);
        bgimage.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bgimage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        radwalk = new javax.swing.JRadioButton();
        chkentry = new javax.swing.JCheckBox();
        chkpeg = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chkbhel = new javax.swing.JCheckBox();
        chkpani = new javax.swing.JCheckBox();
        bntbudget = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtbudget = new javax.swing.JTextPane();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 700));
        setResizable(false);
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(null);

        bgimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/615646bf24adae1103e5b0273f6242fd.jpg"))); // NOI18N
        jPanel1.add(bgimage);
        bgimage.setBounds(360, 60, 306, 308);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("INFORMATION");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 410, 100, 40);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("ADDRESS");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 520, 60, 16);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("NEAREST RAILWAY STATION");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(10, 590, 170, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 3, 12)); // NOI18N
        jLabel2.setText("KINDLY SELECT ACCORDING TO YOUR BUDGET");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(410, 610, 290, 60);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel25.setText("Note: Kindly Reach the railway station mentioned");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(50, 650, 300, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("HOW TO REACH ?");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 700, 110, 30);

        jLabel4.setText("WALK");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 750, 40, 16);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("ENTRY FEE");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 810, 70, 16);

        jLabel12.setText("ENTRY FEE  50 Rs ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(70, 840, 100, 16);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("ACTIVITIES");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(50, 900, 70, 16);

        jLabel17.setText(" Jijamata Udyan penguin tickets: 100 Rs  ");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(70, 930, 220, 16);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("FOOD");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(50, 980, 43, 16);

        jLabel28.setText("SNACKS  :");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(30, 1030, 60, 16);

        jLabel27.setText("  Byculla Railway Station (W)");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(240, 590, 170, 16);

        jLabel24.setText("Veermata jijabai Bhonsale Udyan Railway Station, 91A, Lalbaug Flyover, near Byculla, Byculla East, Byculla, Mumbai, Maharashtra 400027");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(240, 520, 730, 16);

        jLabel23.setText("of India and consequently referred to as the Victoria Gardens or Rani Baug.");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(210, 460, 770, 20);

        jLabel22.setText("Spread across more than 60 acres in the heart of Mumbai, Rani Baug or the Veermata Jijabai Bhonsale Udyan  is the oldest public garden in the ");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(210, 410, 780, 30);

        jLabel29.setText("financial capital of the nation. Constructed in the year 1861, this verdant landmark of Mumbai was named after Queen Victoria, the then Empress ");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(210, 440, 770, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText(" Veermata Jijabai Bhonsale Udyan");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(390, 20, 250, 16);
        jPanel1.add(radwalk);
        radwalk.setBounds(380, 750, 98, 21);

        chkentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkentryActionPerformed(evt);
            }
        });
        jPanel1.add(chkentry);
        chkentry.setBounds(380, 840, 19, 19);
        jPanel1.add(chkpeg);
        chkpeg.setBounds(380, 930, 19, 19);

        jLabel5.setText("Bestof  sushil panipuri :35 Rs ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 1030, 160, 16);

        jLabel6.setText("  Bhel centre  : 20 Rs");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 1050, 140, 20);
        jPanel1.add(chkbhel);
        chkbhel.setBounds(380, 1050, 85, 19);
        jPanel1.add(chkpani);
        chkpani.setBounds(380, 1030, 19, 19);

        bntbudget.setText("BUDGET");
        bntbudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntbudgetActionPerformed(evt);
            }
        });
        jPanel1.add(bntbudget);
        bntbudget.setBounds(40, 1200, 100, 30);

        jScrollPane1.setViewportView(txtbudget);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(190, 1200, 70, 30);

        jButton7.setText("BACK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(60, 1360, 72, 23);

        jButton1.setText("CLEAR ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(220, 1360, 72, 23);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton2.setText("NEARBY LOCATIONS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(780, 1390, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1060, 1840);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkentryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkentryActionPerformed

    private void bntbudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntbudgetActionPerformed
        // TODO add your handling code here:
        double total;
        double subtotal = 0;

        if(radwalk.isSelected()){
            subtotal=subtotal +0;
        }
        
        if(chkentry.isSelected()){
            subtotal=subtotal + 50;
        }
        if(chkpeg.isSelected()){
            subtotal=subtotal + 100;
        }
        if(chkpani.isSelected()){
            subtotal=subtotal + 35;
        }

        if(chkbhel.isSelected()){
            subtotal=subtotal + 20;
        }
       

        txtbudget.setText("Rs. " + subtotal);
        // txtbudget.setText(Double.toString( subtotal ));

        subtotal=Double.parseDouble(txtbudget.getText());

    }//GEN-LAST:event_bntbudgetActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        home homeFrame = new home();
        homeFrame.setVisible(true);

        // Close the current login frame if needed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        radwalk.setSelected(false);
       
        chkentry.setSelected(false);
        chkentry.setSelected(false);
        chkpeg.setSelected(false);
          chkpani.setSelected(false);
            chkbhel.setSelected(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        if(radwalk.isSelected()){
            JOptionPane.showMessageDialog(null, "Great", "How to reach?", JOptionPane.INFORMATION_MESSAGE);

        }
        else{
            JOptionPane.showMessageDialog(null, "SELECT (HOW TO REACH)", "Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
        // TODO add your handling code here:
             int h = jPanel1.getHeight();
        int a =evt.getWheelRotation();
        int x = jPanel1.getX();
        int y = jPanel1.getY();
        int b = 0;
        if(a>0){
            if(y== this.getHeight()- jPanel1.getHeight()){
                a=0;
            }
            else{
                b+=50;
                jPanel1.setLocation(x, y-b);
                b=0;
            }
        }
        
         if(a<0){
            if(y== 0){
                a=0;
            }
            else{
                b+=50;
                jPanel1.setLocation(x, y+b);
                b=0;
            }
        }
    }//GEN-LAST:event_formMouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(location6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(location6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(location6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(location6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new location6().setVisible(true);
            }
        });
    }

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.jpeg")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgimage;
    private javax.swing.JButton bntbudget;
    private javax.swing.JCheckBox chkbhel;
    private javax.swing.JCheckBox chkentry;
    private javax.swing.JCheckBox chkpani;
    private javax.swing.JCheckBox chkpeg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radwalk;
    private javax.swing.JTextPane txtbudget;
    // End of variables declaration//GEN-END:variables
}
