/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testing;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class location1 extends javax.swing.JFrame {

    /**
     * Creates new form location1
     */
    public location1() {
        initComponents();
         setIconImage();
        
        
         Icon i = bgimage.getIcon();
        ImageIcon icon =(ImageIcon)i;
        Image image = icon.getImage().getScaledInstance(bgimage.getWidth(), bgimage.getHeight(), Image.SCALE_SMOOTH);
        bgimage.setIcon(new ImageIcon(image));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bgimage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        bntbudget = new javax.swing.JButton();
        radwalk = new javax.swing.JRadioButton();
        radbus = new javax.swing.JRadioButton();
        radtaxi = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtbudget = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        chkentry = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        chkboat = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        chkvada = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        chkbir = new javax.swing.JCheckBox();
        chkfish = new javax.swing.JCheckBox();
        chkthali = new javax.swing.JCheckBox();
        chksand = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GATEWAY OF INDIA");
        setMaximumSize(new java.awt.Dimension(1050, 2000));
        setMinimumSize(new java.awt.Dimension(1050, 700));
        setResizable(false);
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(200, 224, 249));
        jPanel1.setLayout(null);

        bgimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/location1.jpg"))); // NOI18N
        jPanel1.add(bgimage);
        bgimage.setBounds(310, 70, 430, 360);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("INFORMATION");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 450, 100, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 3, 12)); // NOI18N
        jLabel2.setText("KINDLY SELECT ACCORDING TO YOUR BUDGET");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(410, 610, 290, 60);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("HOW TO REACH ?");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 700, 110, 30);

        jLabel4.setText("WALK  30 min");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 750, 90, 16);

        jLabel5.setText("    BUS 12min {A107,103,21LTD,6LTD} ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 780, 220, 16);

        jLabel6.setText("TAXI");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 810, 40, 16);

        jLabel7.setText("6 RS");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(420, 780, 60, 16);

        jLabel8.setText("0 Rs");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(220, 890, 40, 16);

        jLabel9.setText("50  RS");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(420, 810, 40, 16);

        jButton7.setText("BACK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(30, 1490, 72, 23);

        bntbudget.setText("BUDGET");
        bntbudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntbudgetActionPerformed(evt);
            }
        });
        jPanel1.add(bntbudget);
        bntbudget.setBounds(50, 1330, 100, 30);

        radwalk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radwalkActionPerformed(evt);
            }
        });
        jPanel1.add(radwalk);
        radwalk.setBounds(480, 750, 55, 21);

        radbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbusActionPerformed(evt);
            }
        });
        jPanel1.add(radbus);
        radbus.setBounds(480, 780, 70, 20);

        radtaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radtaxiActionPerformed(evt);
            }
        });
        jPanel1.add(radtaxi);
        radtaxi.setBounds(480, 810, 70, 20);

        jScrollPane1.setViewportView(txtbudget);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(190, 1330, 70, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("ADDRESS");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 540, 60, 16);

        chkentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkentryActionPerformed(evt);
            }
        });
        jPanel1.add(chkentry);
        chkentry.setBounds(360, 890, 85, 19);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("ENTRY FEE");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 860, 70, 16);

        jLabel12.setText("ENTRY FEE");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(70, 890, 70, 16);

        jLabel13.setText("0 RS");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(420, 750, 60, 16);

        jLabel14.setText("(SELECT ANY ONE)");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(200, 710, 120, 16);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("ACTIVITIES");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(50, 930, 70, 16);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("FOOD");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(50, 1000, 43, 16);

        jLabel17.setText("Boat ride");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(70, 960, 70, 16);

        jLabel18.setText("20/-");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(220, 1030, 30, 16);

        chkboat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboatActionPerformed(evt);
            }
        });
        jPanel1.add(chkboat);
        chkboat.setBounds(360, 960, 60, 19);

        jLabel19.setText("Aram VADA PAV");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(120, 1030, 100, 16);

        jLabel20.setText("70Rs");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(220, 960, 30, 16);
        jPanel1.add(chkvada);
        chkvada.setBounds(360, 1030, 19, 19);

        jButton1.setText("CLEAR ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 1480, 72, 23);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("GATEWAY OF INDIA");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(450, 20, 140, 30);

        jLabel22.setText("The Gateway of India is an arch-monument completed in 1924 on the waterfront of Mumbai (Bombay), India.");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(230, 450, 590, 30);

        jLabel23.setText(" It was erected to commemorate the landing of King-Emperor George V, the first British monarch to visit India, in December 1911 .");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(230, 480, 700, 20);

        jLabel24.setText("Apollo Bandar, Colaba, Mumbai, Maharashtra 400001 ");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(230, 540, 290, 16);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton2.setText("NEARBY LOCATIONS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(780, 1480, 130, 30);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel25.setText("Note: Kindly Reach the railway station mentioned");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(50, 650, 300, 16);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("NEAREST RAILWAY STATION");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(10, 590, 170, 16);

        jLabel27.setText(" CSMT  RAILWAY STATION");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(240, 590, 150, 16);

        jLabel28.setText("SNACKS  :");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(30, 1030, 60, 16);

        jLabel29.setText("    Bombay sandwich 45/- ");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(100, 1050, 150, 16);

        jLabel30.setText("LUNCH/DINNER  :");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(10, 1120, 110, 16);

        jLabel31.setText("Bagdadi Restaurant ");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(130, 1120, 230, 16);

        jLabel32.setText("chicken biryani 195/-");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(130, 1140, 110, 16);

        jLabel33.setText("fish fry 210/-");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(130, 1160, 100, 16);

        jLabel34.setText("Chetna Restaurant  ");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(130, 1210, 140, 16);

        jLabel35.setText("veg thali 200/- ");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(130, 1250, 110, 16);

        chkbir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbirActionPerformed(evt);
            }
        });
        jPanel1.add(chkbir);
        chkbir.setBounds(360, 1140, 19, 19);
        jPanel1.add(chkfish);
        chkfish.setBounds(360, 1160, 19, 19);
        jPanel1.add(chkthali);
        chkthali.setBounds(360, 1250, 85, 19);

        chksand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chksandActionPerformed(evt);
            }
        });
        jPanel1.add(chksand);
        chksand.setBounds(360, 1050, 85, 19);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1050, 2040);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
     int h = jPanel1.getHeight();
        int a =evt.getWheelRotation();
        int x = jPanel1.getX();
        int y = jPanel1.getY();
        int b = 0;
        if(a>0){
            if(y== this.getHeight()- jPanel1.getHeight()){
                a=0;
            }
            else{
                b+=50;
                jPanel1.setLocation(x, y-b);
                b=0;
            }
        }
        
         if(a<0){
            if(y== 0){
                a=0;
            }
            else{
                b+=50;
                jPanel1.setLocation(x, y+b);
                b=0;
            }
        }
    }//GEN-LAST:event_formMouseWheelMoved

    private void bntbudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntbudgetActionPerformed
        // TODO add your handling code here:
        double total;
        double subtotal = 0;
        
        
        if(radwalk.isSelected()){
            subtotal=subtotal +0;
        }else if(radbus.isSelected()){
            subtotal=subtotal + 10;
        }else if (radtaxi.isSelected()){
            subtotal=subtotal + 100;
        }
        
        if(chkentry.isSelected()){
            subtotal=subtotal + 0;
        }
        if(chkboat.isSelected()){
            subtotal=subtotal + 70;
        }
        if(chkvada.isSelected()){
            subtotal=subtotal + 20;
        }
        
         if(chksand.isSelected()){
            subtotal=subtotal + 45;
        }
          if(chkbir.isSelected()){
            subtotal=subtotal + 195;
        }
          
           if(chkfish.isSelected()){
            subtotal=subtotal + 210;
        }
           
            if(chkthali.isSelected()){
            subtotal=subtotal + 200;
        }
            
            
        txtbudget.setText("Rs. " + subtotal);
       // txtbudget.setText(Double.toString( subtotal ));
        
        subtotal=Double.parseDouble(txtbudget.getText());
        
    }//GEN-LAST:event_bntbudgetActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        home homeFrame = new home();
        homeFrame.setVisible(true);

        // Close the current login frame if needed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void radwalkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radwalkActionPerformed
        // TODO add your handling code here:
        if(radwalk.isSelected()){
            radbus.setSelected(false);
            radtaxi.setSelected(false);
             JOptionPane.showMessageDialog(null, "Travel Method Selected", "How to reach?", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_radwalkActionPerformed

    private void radbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbusActionPerformed
        // TODO add your handling code here:
        if(radbus.isSelected()){
            radwalk.setSelected(false);
            radtaxi.setSelected(false);
             JOptionPane.showMessageDialog(null, "Travel Method Selected", "How to reach?", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_radbusActionPerformed

    private void radtaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radtaxiActionPerformed
        // TODO add your handling code here:
        if(radtaxi.isSelected()){
            radbus.setSelected(false);
            radwalk.setSelected(false);
             JOptionPane.showMessageDialog(null, "Travel Method Selected", "How to reach?", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_radtaxiActionPerformed

    private void chkentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkentryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkentryActionPerformed

    private void chkboatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkboatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        radwalk.setSelected(false);
        radbus.setSelected(false);
        radtaxi.setSelected(false);
        chkentry.setSelected(false);
        chkboat.setSelected(false);
        chkvada.setSelected(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         if(radwalk.isSelected() || radbus.isSelected()|| radtaxi.isSelected()){
             JOptionPane.showMessageDialog(null, "Great", "How to reach?", JOptionPane.INFORMATION_MESSAGE); 
             
         }
         else{
              JOptionPane.showMessageDialog(null, "SELECT (HOW TO REACH)", "Error", JOptionPane.ERROR_MESSAGE);
              
         }
 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void chksandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chksandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chksandActionPerformed

    private void chkbirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkbirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(location1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(location1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(location1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(location1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new location1().setVisible(true);
            }
        });
    }

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.jpeg")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgimage;
    private javax.swing.JButton bntbudget;
    private javax.swing.JCheckBox chkbir;
    private javax.swing.JCheckBox chkboat;
    private javax.swing.JCheckBox chkentry;
    private javax.swing.JCheckBox chkfish;
    private javax.swing.JCheckBox chksand;
    private javax.swing.JCheckBox chkthali;
    private javax.swing.JCheckBox chkvada;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radbus;
    private javax.swing.JRadioButton radtaxi;
    private javax.swing.JRadioButton radwalk;
    private javax.swing.JTextPane txtbudget;
    // End of variables declaration//GEN-END:variables
}
