/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testing;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class location7 extends javax.swing.JFrame {

    /**
     * Creates new form location7
     */
    public location7() {
        initComponents();
          Icon i = bgimage.getIcon();
           setIconImage();
        ImageIcon icon =(ImageIcon)i;
        Image image = icon.getImage().getScaledInstance(bgimage.getWidth(), bgimage.getHeight(), Image.SCALE_SMOOTH);
        bgimage.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        bgimage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        bntbudget = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtbudget = new javax.swing.JTextPane();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        chkentry = new javax.swing.JCheckBox();
        radwalk = new javax.swing.JRadioButton();
        radbus = new javax.swing.JRadioButton();
        radtaxi = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        chkbhaji = new javax.swing.JCheckBox();
        chkride = new javax.swing.JCheckBox();
        chkmini = new javax.swing.JCheckBox();
        chkminic = new javax.swing.JCheckBox();
        chktiger = new javax.swing.JCheckBox();
        chktigerc = new javax.swing.JCheckBox();
        chkcombine = new javax.swing.JCheckBox();
        chkcombinec = new javax.swing.JCheckBox();
        chkboat4 = new javax.swing.JCheckBox();
        chkboat2 = new javax.swing.JCheckBox();
        chkcycle = new javax.swing.JCheckBox();
        chkcaves = new javax.swing.JCheckBox();
        chkcamera = new javax.swing.JCheckBox();
        chkmaggi = new javax.swing.JCheckBox();
        chkmisal = new javax.swing.JCheckBox();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sanjay Gandhi National Park");
        setMinimumSize(new java.awt.Dimension(1060, 700));
        setResizable(false);
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(199, 239, 239));
        jPanel1.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Sanjay Gandhi National Park");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(450, 20, 210, 30);

        bgimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/7af5004b299195709ba596c707ab6b40.jpg"))); // NOI18N
        jPanel1.add(bgimage);
        bgimage.setBounds(310, 70, 430, 360);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("INFORMATION");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 450, 100, 40);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("ADDRESS");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 540, 60, 16);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("NEAREST RAILWAY STATION");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(10, 590, 170, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 3, 12)); // NOI18N
        jLabel2.setText("KINDLY SELECT ACCORDING TO YOUR BUDGET");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(410, 610, 290, 60);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel25.setText("Note: Kindly Reach the railway station mentioned");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(50, 650, 300, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("HOW TO REACH ?");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 700, 110, 30);

        jLabel14.setText("(SELECT ANY ONE)");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(200, 710, 120, 16);

        jLabel4.setText("WALK   17 min ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 750, 90, 16);

        jLabel6.setText("TAXI");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 810, 40, 16);

        jLabel5.setText("    BUS  (209,709LTD,C-60exp)");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 780, 220, 16);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("ENTRY FEE");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 860, 70, 16);

        jLabel12.setText("ENTRY FEE");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(70, 890, 70, 16);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("ACTIVITIES");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(50, 930, 70, 16);

        jLabel17.setText("Combined Tiger & Lion safari for Adults                                         Rs 81 per person");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(40, 1100, 440, 16);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("FOOD");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(30, 1320, 43, 16);

        jLabel28.setText("SNACKS  :");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(30, 1360, 60, 16);

        bntbudget.setText("BUDGET");
        bntbudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntbudgetActionPerformed(evt);
            }
        });
        jPanel1.add(bntbudget);
        bntbudget.setBounds(70, 1510, 100, 30);

        jScrollPane1.setViewportView(txtbudget);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(240, 1510, 70, 30);

        jButton7.setText("BACK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(40, 1610, 72, 23);

        jButton1.setText("CLEAR ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 1610, 72, 23);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton2.setText("NEARBY LOCATIONS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(800, 1600, 130, 30);

        chkentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkentryActionPerformed(evt);
            }
        });
        jPanel1.add(chkentry);
        chkentry.setBounds(480, 890, 85, 19);

        radwalk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radwalkActionPerformed(evt);
            }
        });
        jPanel1.add(radwalk);
        radwalk.setBounds(480, 750, 55, 21);

        radbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbusActionPerformed(evt);
            }
        });
        jPanel1.add(radbus);
        radbus.setBounds(480, 780, 70, 20);

        radtaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radtaxiActionPerformed(evt);
            }
        });
        jPanel1.add(radtaxi);
        radtaxi.setBounds(480, 810, 70, 20);

        jLabel22.setText("Sanjay Gandhi National Park (SGNP), is an 87 km2 (34 sq mi) protected area in Mumbai, Maharashtra. It was established in 1969");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(230, 450, 680, 30);

        jLabel23.setText(" with its headquarters situated at Borivali. The 2400-year-old Kanheri caves, sculpted by monks out of the rocky basaltic cliffs, lie within the park.");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(230, 470, 770, 20);

        jLabel24.setText("Borivali East, Mumbai, Maharashtra 400066");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(230, 540, 290, 16);

        jLabel27.setText("Borivali RAILWAY STATION");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(240, 590, 150, 16);

        jLabel7.setText("5 RS");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(420, 780, 40, 16);

        jLabel8.setText("45 Rs");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(420, 890, 40, 16);

        jLabel9.setText("400  RS");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(420, 810, 40, 16);

        jLabel13.setText("Safari ride:                                                                                                        70 Rs");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(40, 960, 430, 16);

        jLabel18.setText(" Adult Mini Train                                                                            50 rs. per person");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(40, 980, 420, 16);

        jLabel19.setText("Child Mini Train                                                                                Rs19 per person ");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(40, 1010, 430, 16);

        jLabel20.setText("Tiger safari for Adults                                                                     Rs 70 per person ");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(40, 1040, 430, 16);

        jLabel29.setText("Tiger safari for Children                                                                   Rs 28 per person");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(40, 1070, 430, 16);

        jLabel31.setText("Combined Tiger & Lion safari for Children                                       Rs32 per person");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(40, 1120, 440, 16);

        jLabel32.setText(" Boat                                                                                                    Rs 97 for 4-seater");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(40, 1140, 430, 16);

        jLabel33.setText("Boat                                                                                                 Rs 48 for 2-seater ");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(40, 1160, 430, 16);

        jLabel34.setText("Cycle rent                                                                                                          Rs 60 ");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(40, 1180, 430, 16);

        jLabel35.setText("Shuttle bus that runs from the park entrance to the caves             Rs 60 per person ");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(40, 1200, 430, 16);

        jLabel36.setText(" Still Camera                                                                                                      50 Rs");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(40, 1230, 430, 16);

        jLabel37.setText("  maggi 30");
        jPanel1.add(jLabel37);
        jLabel37.setBounds(120, 1360, 90, 16);

        jLabel38.setText("authentic misal pav 50");
        jPanel1.add(jLabel38);
        jLabel38.setBounds(120, 1380, 140, 16);

        jLabel39.setText("Bhaji 30");
        jPanel1.add(jLabel39);
        jLabel39.setBounds(120, 1400, 80, 16);
        jPanel1.add(chkbhaji);
        chkbhaji.setBounds(480, 1390, 85, 20);
        jPanel1.add(chkride);
        chkride.setBounds(480, 960, 19, 19);
        jPanel1.add(chkmini);
        chkmini.setBounds(480, 980, 60, 20);
        jPanel1.add(chkminic);
        chkminic.setBounds(480, 1010, 85, 20);
        jPanel1.add(chktiger);
        chktiger.setBounds(480, 1040, 85, 20);
        jPanel1.add(chktigerc);
        chktigerc.setBounds(480, 1070, 85, 20);
        jPanel1.add(chkcombine);
        chkcombine.setBounds(480, 1100, 85, 20);
        jPanel1.add(chkcombinec);
        chkcombinec.setBounds(480, 1120, 85, 20);
        jPanel1.add(chkboat4);
        chkboat4.setBounds(480, 1140, 85, 20);
        jPanel1.add(chkboat2);
        chkboat2.setBounds(480, 1160, 85, 20);
        jPanel1.add(chkcycle);
        chkcycle.setBounds(480, 1180, 85, 20);
        jPanel1.add(chkcaves);
        chkcaves.setBounds(480, 1200, 85, 20);
        jPanel1.add(chkcamera);
        chkcamera.setBounds(480, 1230, 85, 20);
        jPanel1.add(chkmaggi);
        chkmaggi.setBounds(480, 1350, 85, 20);
        jPanel1.add(chkmisal);
        chkmisal.setBounds(480, 1370, 85, 20);

        jLabel30.setText("The rich flora and fauna of the Sanjay Gandhi National Park attract more than 2 million visitors every year.");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(230, 490, 750, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 1060, 1930);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bntbudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntbudgetActionPerformed
        // TODO add your handling code here:
        double total;
        double subtotal = 0;

        if(radwalk.isSelected()){
            subtotal=subtotal +0;
        }else if(radbus.isSelected()){
            subtotal=subtotal + 5;
        }else if (radtaxi.isSelected()){
            subtotal=subtotal + 400;
        }

        if(chkentry.isSelected()){
            subtotal=subtotal + 45;
        }
        if(chkride.isSelected()){
            subtotal=subtotal + 70;
        }
        if(chkmini.isSelected()){
            subtotal=subtotal + 50;
        }

        if(chkminic.isSelected()){
            subtotal=subtotal + 19;
        }
        if(chktiger.isSelected()){
            subtotal=subtotal + 70;
        }

        if(chktigerc.isSelected()){
            subtotal=subtotal + 28;
        }

        if(chkcombine.isSelected()){
            subtotal=subtotal + 81;
        }
         if(chkcombinec.isSelected()){
            subtotal=subtotal + 32;
        }
          if(chkboat4.isSelected()){
            subtotal=subtotal + 97;
        }
           if(chkboat2.isSelected()){
            subtotal=subtotal + 48;
        }
           
            if(chkcycle.isSelected()){
            subtotal=subtotal + 60;
        }
             if(chkcaves.isSelected()){
            subtotal=subtotal + 60;
        }
              if(chkcamera.isSelected()){
            subtotal=subtotal + 50;
        }
               if(chkmaggi.isSelected()){
            subtotal=subtotal + 30;
        }
                if(chkmisal.isSelected()){
            subtotal=subtotal + 50;
        }
                 if(chkbhaji.isSelected()){
            subtotal=subtotal + 30;
        }

        txtbudget.setText("Rs. " + subtotal);
        // txtbudget.setText(Double.toString( subtotal ));

        subtotal=Double.parseDouble(txtbudget.getText());

    }//GEN-LAST:event_bntbudgetActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        home homeFrame = new home();
        homeFrame.setVisible(true);

        // Close the current login frame if needed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        radwalk.setSelected(false);
        radbus.setSelected(false);
        radtaxi.setSelected(false);
        chkentry.setSelected(false);
        chkride.setSelected(false);
        chkmini.setSelected(false);
        chkminic.setSelected(false);
        chktiger.setSelected(false);
          chktigerc.setSelected(false);
            chkcombine.setSelected(false);
             chkcombinec.setSelected(false);
              chkboat4.setSelected(false);
              chkboat2.setSelected(false);
              chkcycle.setSelected(false);
              chkcaves.setSelected(false);
              chkcamera.setSelected(false);
              chkmaggi.setSelected(false);
          chkmisal.setSelected(false);
          chkbhaji.setSelected(false);
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        if(radwalk.isSelected() || radbus.isSelected()|| radtaxi.isSelected()){
            JOptionPane.showMessageDialog(null, "Great", "How to reach?", JOptionPane.INFORMATION_MESSAGE);

        }
        else{
            JOptionPane.showMessageDialog(null, "SELECT (HOW TO REACH)", "Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void chkentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkentryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkentryActionPerformed

    private void radwalkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radwalkActionPerformed
        // TODO add your handling code here:
        if(radwalk.isSelected()){
            radbus.setSelected(false);
            radtaxi.setSelected(false);
            JOptionPane.showMessageDialog(null, "Travel Method Selected", "How to reach?", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_radwalkActionPerformed

    private void radbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbusActionPerformed
        // TODO add your handling code here:
        if(radbus.isSelected()){
            radwalk.setSelected(false);
            radtaxi.setSelected(false);
            JOptionPane.showMessageDialog(null, "Travel Method Selected", "How to reach?", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_radbusActionPerformed

    private void radtaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radtaxiActionPerformed
        // TODO add your handling code here:
        if(radtaxi.isSelected()){
            radbus.setSelected(false);
            radwalk.setSelected(false);
            JOptionPane.showMessageDialog(null, "Travel Method Selected", "How to reach?", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_radtaxiActionPerformed

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
        // TODO add your handling code here:
        int h = jPanel1.getHeight();
        int a =evt.getWheelRotation();
        int x = jPanel1.getX();
        int y = jPanel1.getY();
        int b = 0;
        if(a>0){
            if(y== this.getHeight()- jPanel1.getHeight()){
                a=0;
            }
            else{
                b+=50;
                jPanel1.setLocation(x, y-b);
                b=0;
            }
        }
        
         if(a<0){
            if(y== 0){
                a=0;
            }
            else{
                b+=50;
                jPanel1.setLocation(x, y+b);
                b=0;
            }
        }
    }//GEN-LAST:event_formMouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(location7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(location7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(location7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(location7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new location7().setVisible(true);
            }
        });
    }
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.jpeg")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgimage;
    private javax.swing.JButton bntbudget;
    private javax.swing.JCheckBox chkbhaji;
    private javax.swing.JCheckBox chkboat2;
    private javax.swing.JCheckBox chkboat4;
    private javax.swing.JCheckBox chkcamera;
    private javax.swing.JCheckBox chkcaves;
    private javax.swing.JCheckBox chkcombine;
    private javax.swing.JCheckBox chkcombinec;
    private javax.swing.JCheckBox chkcycle;
    private javax.swing.JCheckBox chkentry;
    private javax.swing.JCheckBox chkmaggi;
    private javax.swing.JCheckBox chkmini;
    private javax.swing.JCheckBox chkminic;
    private javax.swing.JCheckBox chkmisal;
    private javax.swing.JCheckBox chkride;
    private javax.swing.JCheckBox chktiger;
    private javax.swing.JCheckBox chktigerc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radbus;
    private javax.swing.JRadioButton radtaxi;
    private javax.swing.JRadioButton radwalk;
    private javax.swing.JTextPane txtbudget;
    // End of variables declaration//GEN-END:variables
}
